package vendedor;

import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import main.Subasta;

/**
 *
 * @author User
 */
public class InterfazVendedor extends javax.swing.JFrame {

    private final Vendedor vendedor;

    /**
     * Creates new form InterfazVendedor
     *
     * @param vendedor
     */
    public InterfazVendedor(Vendedor vendedor) {
        initComponents();
        btnIntroducir.setEnabled(false);
        this.vendedor = vendedor;
        listaSubastas.setModel(new DefaultListModel<>());
    }

    public void actualizarSubasta(Subasta subasta) {

        switch (subasta.getEstado()) {
            // Se a subasta esta en curso, actualizamos os valores da taboa
            case Subasta.ESTADO_1:

                for (int i = 0; i < taboaSubastas.getRowCount(); i++) {
                    if (taboaSubastas.getValueAt(i, 0).equals(subasta.getIdSubasta())) {
                        taboaSubastas.setValueAt(subasta.getRonda(), i, 2);
                        taboaSubastas.setValueAt(subasta.getPrezoActual(), i, 3);
                        taboaSubastas.setValueAt(subasta.getGanhador(), i, 4);
                        taboaSubastas.setValueAt(subasta.getEstado(), i, 5);
                        break;
                    }
                }
                break;
            // Se a subasta finaliza, actualizamos os valores da taboa e 
            // engadimos a lista de libros vendidos o libro
            case Subasta.ESTADO_2:

                for (int i = 0; i < taboaSubastas.getRowCount(); i++) {
                    if (taboaSubastas.getValueAt(i, 0).equals(subasta.getIdSubasta())) {
                        taboaSubastas.setValueAt(subasta.getRonda(), i, 2);
                        taboaSubastas.setValueAt(subasta.getPrezoActual(), i, 3);
                        taboaSubastas.setValueAt(subasta.getGanhador(), i, 4);
                        taboaSubastas.setValueAt(subasta.getEstado(), i, 5);
                        break;
                    }
                }
                // Engadimos a lista de libros vendidos o libro
                ((DefaultListModel) listaSubastas.getModel()).add(0, subasta.getTitulo() + " | " + subasta.getPrezoActual() + " € | " + subasta.getGanhador());
                break;
            // En caso de que a subasta ainda non estea en curso, engadimos a 
            // subasta a taboa se non estaba
            case Subasta.ESTADO_0:

                int index = -1;
                for (int i = 0; i < taboaSubastas.getRowCount(); i++) {
                    if (taboaSubastas.getValueAt(i, 0).equals(subasta.getIdSubasta())) {
                        index = i;
                        break;
                    }
                }
                // Se a subasta non esta na taboa engadimola
                if (index == -1) {
                    Object[] fila = new Object[]{subasta.getIdSubasta(), subasta.getTitulo(), subasta.getRonda(), subasta.getPrezoActual(), subasta.getGanhador(), subasta.getEstado()};
                    ((DefaultTableModel) taboaSubastas.getModel()).addRow(fila);
                }
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaSubastas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtPrezo = new javax.swing.JTextField();
        txtIncremento = new javax.swing.JTextField();
        btnIntroducir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taboaSubastas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane2.setViewportView(listaSubastas);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Introduce un libro no catalogo: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Titulo: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Prezo inicial: ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Incremento:");

        txtTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letraEscrita(evt);
            }
        });

        txtPrezo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtPrezo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letraEscrita(evt);
            }
        });

        txtIncremento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtIncremento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letraEscrita(evt);
            }
        });

        btnIntroducir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnIntroducir.setText("Introducir");
        btnIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducirActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Libros vendidos: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIntroducir)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPrezo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                                        .addComponent(txtIncremento, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrezo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIntroducir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        taboaSubastas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdSubasta", "Titulo", "Ronda", "Prezo", "Ganhador", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(taboaSubastas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducirActionPerformed
        if (!txtTitulo.getText().isBlank() && !txtPrezo.getText().isBlank() && !txtIncremento.getText().isBlank()) {
            vendedor.actualizarCatalogo(txtTitulo.getText(), Float.parseFloat(txtPrezo.getText()), Integer.parseInt(txtIncremento.getText()));
            txtTitulo.setText("");
            txtPrezo.setText("");
            txtIncremento.setText("");
            btnIntroducir.setEnabled(false);
        }
    }//GEN-LAST:event_btnIntroducirActionPerformed

    private void letraEscrita(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letraEscrita
        if (txtTitulo.getText().isBlank()) {
            btnIntroducir.setEnabled(false);
        } else {
            btnIntroducir.setEnabled(true);

        }    }//GEN-LAST:event_letraEscrita

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntroducir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaSubastas;
    private javax.swing.JTable taboaSubastas;
    private javax.swing.JTextField txtIncremento;
    private javax.swing.JTextField txtPrezo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
