package comprador;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import ontoloxiaSubasta.Subasta;

/**
 *
 * @author Anton Gomez Lopez
 */
public class InterfazComprador extends javax.swing.JFrame {

    private final Comprador comprador;
    protected final ArrayList<Subasta> subastas;

    /**
     * Creates new form InterfazComprador
     *
     * @param comprador
     */
    public InterfazComprador(Comprador comprador) {
        initComponents();
        this.comprador = comprador;
        listaSubastas.setModel(new DefaultListModel<>());
        listaLibrosSenSubasta.setModel(new DefaultListModel<>());
        subastas = new ArrayList<>();
    }

    public void actualizarSubasta(Subasta subasta) {
        int flag = 0;
        // Se a subasta esta en curso, buscamos a subasta e se a atopamos
        // modificamos os seus valores. En caso de non atopala, engadimos a 
        // subasta a lista
        if (subasta.getEstado().equals(Subasta.ESTADO_1)) {

            for (int i = 0; i < taboaSubastas.getRowCount(); i++) {
                if (taboaSubastas.getValueAt(i, 0).equals(subasta.getIdSubasta())) {
                    taboaSubastas.setValueAt(subasta.getRonda(), i, 2);
                    taboaSubastas.setValueAt(subasta.getPrezo(), i, 3);
                    if (subasta.getGanhador() == null) {
                        taboaSubastas.setValueAt(" - ", i, 4);
                    } else {
                        taboaSubastas.setValueAt(subasta.getGanhador().getLocalName(), i, 4);
                    }
                    taboaSubastas.setValueAt(subasta.getEstado(), i, 5);
                    flag = 1;
                    break;
                }
            }
            // Non atopamos a subasta, engadimola a taboa
            if (flag == 0) {
                Object[] fila;
                if (subasta.getGanhador() == null) {
                    fila = new Object[]{subasta.getIdSubasta(), subasta.getTitulo(),
                        subasta.getRonda(), subasta.getPrezo(), " - ", subasta.getEstado()};
                } else {
                    fila = new Object[]{subasta.getIdSubasta(), subasta.getTitulo(),
                        subasta.getRonda(), subasta.getPrezo(), subasta.getGanhador().getLocalName(), subasta.getEstado()};
                }
                ((DefaultTableModel) taboaSubastas.getModel()).addRow(fila);
            }
        } else if (subasta.getEstado().equals(Subasta.ESTADO_2)) {

            // Obtemos a fila da taboa e modificamola
            for (int i = 0; i < taboaSubastas.getRowCount(); i++) {
                if (taboaSubastas.getValueAt(i, 0).equals(subasta.getIdSubasta())) {
                    taboaSubastas.setValueAt(subasta.getRonda(), i, 2);
                    taboaSubastas.setValueAt(subasta.getPrezo(), i, 3);
                    if (subasta.getGanhador() == null) {
                        taboaSubastas.setValueAt(" - ", i, 4);
                    } else {
                        taboaSubastas.setValueAt(subasta.getGanhador().getLocalName(), i, 4);
                    }
                    taboaSubastas.setValueAt(subasta.getEstado(), i, 5);
                    break;
                }
            }
            // No caso de que sexa ganhador, eliminamos o libro da lista de libros en
            // busca de subastas e engadimola a lista de libros comprados
            if (comprador.getAID().equals(subasta.getGanhador())) {
                int index = -1;

                ((DefaultListModel) listaSubastas.getModel()).add(0, subasta.getTitulo() + ", " + subasta.getPrezo() + " €");

                DefaultListModel modelo = (DefaultListModel) listaLibrosSenSubasta.getModel();
                for (int i = (modelo.size() - 1); i >= 0; i--) {
                    String[] campos = ((String) modelo.get(i)).split(", ");
                    if (campos[0].equals(subasta.getTitulo())) {
                        index = i;
                        break;
                    }
                }
                if (index != -1) {
                    modelo.remove(index);
                }

                comprador.getLibros().remove(subasta.getTitulo());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        panelEsquerdo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIntroducir = new javax.swing.JButton();
        txtPrezoMax = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaSubastas = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaLibrosSenSubasta = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taboaSubastas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel1.setText("Título: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel2.setText("Prezo máximo:");

        btnIntroducir.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnIntroducir.setText("Introducir");
        btnIntroducir.setEnabled(false);
        btnIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroducirActionPerformed(evt);
            }
        });

        txtPrezoMax.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtPrezoMax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letraEscrita(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                letraEscrita(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel3.setText("Introduce un libro");

        listaSubastas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        listaSubastas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaSubastas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaSubastas.setName(""); // NOI18N
        jScrollPane1.setViewportView(listaSubastas);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel4.setText("Libros comprados: ");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel5.setText("Libros buscando subasta: ");

        listaLibrosSenSubasta.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        listaLibrosSenSubasta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaLibrosSenSubasta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaLibrosSenSubasta.setName(""); // NOI18N
        jScrollPane3.setViewportView(listaLibrosSenSubasta);

        javax.swing.GroupLayout panelEsquerdoLayout = new javax.swing.GroupLayout(panelEsquerdo);
        panelEsquerdo.setLayout(panelEsquerdoLayout);
        panelEsquerdoLayout.setHorizontalGroup(
            panelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEsquerdoLayout.createSequentialGroup()
                .addGroup(panelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelEsquerdoLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelEsquerdoLayout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addGroup(panelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelEsquerdoLayout.createSequentialGroup()
                                .addGroup(panelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(panelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelEsquerdoLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnIntroducir))
                                    .addComponent(txtPrezoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTitulo)))
                            .addGroup(panelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelEsquerdoLayout.setVerticalGroup(
            panelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEsquerdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrezoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIntroducir)
                .addGap(42, 42, 42))
        );

        taboaSubastas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        taboaSubastas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdSubasta", "Titulo", "Ronda", "Prezo", "Ganhador", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(taboaSubastas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEsquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEsquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void letraEscrita(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_letraEscrita
        if (txtTitulo.getText().isBlank()) {
            btnIntroducir.setEnabled(false);
        } else {
            btnIntroducir.setEnabled(true);
        }
    }//GEN-LAST:event_letraEscrita

    private void btnIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroducirActionPerformed
        if (!txtPrezoMax.getText().isBlank() && !txtTitulo.getText().isBlank()) {
            ((DefaultListModel) listaLibrosSenSubasta.getModel()).addElement(txtTitulo.getText() + ", " + txtPrezoMax.getText() + " €");
            comprador.actualizarLibrosInterese(txtTitulo.getText(), Float.parseFloat(txtPrezoMax.getText()));
            txtTitulo.setText("");
            txtPrezoMax.setText("");
            btnIntroducir.setEnabled(false);
        }
    }//GEN-LAST:event_btnIntroducirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntroducir;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaLibrosSenSubasta;
    private javax.swing.JList<String> listaSubastas;
    private javax.swing.JPanel panelEsquerdo;
    private javax.swing.JTable taboaSubastas;
    private javax.swing.JTextField txtPrezoMax;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
